//DUT
../hdl/designs/tx/encoder.sv
../hdl/designs/tx/PISO.sv
../hdl/designs/rx/cdr/sampler.sv
../hdl/designs/rx/cdr/phase_detector.sv
../hdl/designs/rx/cdr/loop_filter.sv
../hdl/designs/rx/cdr/cdr.sv
../hdl/designs/rx/elastic_buffer/buffer_memory.sv
../hdl/designs/rx/elastic_buffer/buffer_read.sv
../hdl/designs/rx/elastic_buffer/buffer_write.sv
../hdl/designs/rx/elastic_buffer/synchronizer.sv
../hdl/designs/rx/elastic_buffer/elastic_buffer.sv
../hdl/designs/rx/SIPO.sv
../hdl/designs/rx/decoder.sv
../hdl/designs/rx/receiver_status.sv
../hdl/designs/top_module.sv

analog_blocks/common/channel.sv
analog_blocks/tx/equalizer.sv
analog_blocks/rx/cdr/phase_interpolator.sv
analog_blocks/tx/equalization/clock_generator.sv
analog_blocks/tx/equalization/eye_sampler.sv
analog_blocks/tx/equalization/eye_calculation.sv
analog_blocks/tx/equalization/parameter_update.sv
analog_blocks/tx/equalization/channel_estimation.sv

//interface
enums_pkg.sv
system_testing/top_if.sv
system_testing/assertions_top.sv

//UVM
system_testing/sequence_item_top.sv
system_testing/sequence_top.sv
sequencer.sv
system_testing/driver_top.sv
system_testing/monitor_top.sv
system_testing/agent_top.sv
system_testing/scoreboard_top.sv
env.sv
test.sv
top.sv
