function hdlverifier_compile(vivado_path)
% hdlverifier_compile is a MATLAB calling wrapper for compiling/elaborating the HDL design
% Generated by Cosimulation Wizard on 19-Jun-2025 19:44:37

% ---- set path info for Vivado executables and kernel libs
lutils('PathPrepend', 'PATH', strcat(vivado_path, '\2019.1\bin\..\lib\win64.o'));
lutils('PathPrepend', 'PATH', strcat(vivado_path, '\2019.1\bin'));

% ---- make system call to Vivado script
[s, r] = system(['vivado -mode tcl < hdlverifier_compile.tcl'],'-echo');

if (s ~= 0)
    error(message('HDLLink:CosimWizard:CompilationError',r));
end
